#!/usr/bin/env node
// Regenerates the rule table and the ported test suite from upstream.
//
//   node tools/generate.js [path-or-url-to/llm-cliche-highlighter.html]
//
// Defaults to fetching the current version from simonw/tools. Writes:
//   src/rules.rs             the rule table
//   tests/generated/cases.rs upstream's `patternCases`
//   tests/fixtures/example.txt  upstream's EXAMPLE text
//
// Everything else in the port is hand-written; only these three are generated.

const fs = require('fs');
const path = require('path');

const UPSTREAM =
  'https://raw.githubusercontent.com/simonw/tools/main/llm-cliche-highlighter.html';
const root = path.join(__dirname, '..');

async function source(arg) {
  if (!arg) return (await fetch(UPSTREAM)).text();
  if (/^https?:\/\//.test(arg)) return (await fetch(arg)).text();
  return fs.readFileSync(arg, 'utf8');
}

const cut = (html, name) =>
  html.split(`// ==== ${name} start ====`)[1].split(`// ==== ${name} end ====`)[0];

// A Rust raw string. `##` delimiters clear the ASCII double quotes that appear
// inside a couple of the patterns.
const raw = s => 'r##"' + s + '"##';

// JS regex source -> Rust fancy-regex source. \uXXXX escapes become literal
// characters (the regex crate spells them \x{...}, but these are all visible
// punctuation and read better as themselves), and an /i flag becomes (?i).
const convert = (source, flags) =>
  (flags && flags.includes('i') ? '(?i)' : '') +
  source
    .replace(/\\u([0-9a-fA-F]{4})/g, (_, h) => String.fromCharCode(parseInt(h, 16)))
    .replace(/\\\//g, '/');

// The GUI showed per-match counts on a badge; the CLI has no such thing.
const describe = d => d.replace(/\s*The badge counts[^.]*\.\s*$/, '').trim();

function extractPatterns(impl) {
  const start = impl.indexOf('const patterns = [');
  const src = impl.slice(start, impl.indexOf('\n];', start) + 3);
  const scope = {
    WIKI_GROUP: 'Signs of AI writing (Wikipedia)',
    makeRegexFinder: re => ({ kind: 'regex', source: re.source, flags: re.flags }),
    makeChainFinder: head => ({ kind: 'chain', head }),
    makeEchoFinder: o => ({ kind: 'echo', ...o }),
    makeQuestionChainFinder: o => ({ kind: 'question', ...o }),
    makeAnaphoraFinder: o => ({ kind: 'anaphora', ...o }),
  };
  const build = new Function(...Object.keys(scope), `${src}; return patterns;`);
  return build(...Object.values(scope));
}

const finderExpr = find => {
  switch (find.kind) {
    case 'regex':
      return `Finder::Regex(${raw(convert(find.source, find.flags))})`;
    case 'chain':
      return `Finder::Chain(${raw(convert(find.head, ''))})`;
    case 'echo':
      return `Finder::Echo { min_gram: ${find.minGram}, min_run: ${find.minRun} }`;
    case 'question':
      return `Finder::QuestionChain { min_run: ${find.minRun} }`;
    case 'anaphora':
      return `Finder::Anaphora { min_run: ${find.minRun} }`;
    default:
      throw new Error(`unknown finder kind ${find.kind}`);
  }
};

function rulesRs(patterns) {
  const entries = patterns
    .map(
      p => `    Rule {
        id: ${raw(p.id)},
        name: ${raw(p.name)},
        description: ${raw(describe(p.description))},
        group: ${p.group === undefined ? 'None' : `Some(${raw(p.group)})`},
        finder: ${finderExpr(p.find)},
    },`
    )
    .join('\n');

  return `// @generated by tools/generate.js from Simon Willison's llm-cliche-highlighter.html
// https://github.com/simonw/tools/blob/main/llm-cliche-highlighter.html
//
// Do not edit by hand. The regex sources are the upstream JavaScript literals
// with \\uXXXX escapes resolved and an /i flag rewritten to an inline (?i).

use crate::finders::Finder;

/// One cliche pattern: a stable id, a human-readable name used as the
/// diagnostic message, and the detector that finds it.
pub struct Rule {
    pub id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub group: Option<&'static str>,
    pub finder: Finder,
}

/// Every rule, in upstream declaration order. Order is load-bearing: when two
/// rules match the same span, the earlier one wins (see \`crate::lint\`).
pub static RULES: &[Rule] = &[
${entries}
];
`;
}

function casesRs(tests) {
  const start = tests.indexOf('const patternCases = [');
  const src = tests.slice(start, tests.indexOf('\n];', start) + 3);
  const cases = new Function(`${src}; return patternCases;`)();
  const rows = cases
    .map(([id, sample, expect]) => `    (${raw(id)}, ${raw(sample)}, ${expect}),`)
    .join('\n');

  return `// @generated by tools/generate.js — do not edit by hand.

/// Upstream's \`patternCases\`: (rule id, sample text, expected match count).
///
/// Upstream also asserts per-chain item counts, which drove the GUI badges and
/// have no counterpart here, so only the match counts come across.
pub static PATTERN_CASES: &[(&str, &str, usize)] = &[
${rows}
];
`;
}

function exampleText(impl) {
  const open = 'const EXAMPLE = `';
  const start = impl.indexOf(open) + open.length;
  return impl.slice(start, impl.indexOf('`;', start)).replace(/\\`/g, '`').replace(/\\\$/g, '$');
}

async function main() {
  const html = await source(process.argv[2]);
  const impl = cut(html, 'impl');
  const patterns = extractPatterns(impl);

  const write = (rel, body) => {
    const dest = path.join(root, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, body);
    console.log(`wrote ${rel}`);
  };

  write('src/rules.rs', rulesRs(patterns));
  write('tests/generated/cases.rs', casesRs(cut(html, 'tests')));
  write('tests/fixtures/example.txt', exampleText(impl));
  console.log(`${patterns.length} rules`);
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
