#!/usr/bin/env node
// Regenerates the rule table and test cases from upstream.

const fs = require('fs');
const path = require('path');

const UPSTREAM =
  'https://raw.githubusercontent.com/simonw/tools/main/llm-cliche-highlighter.html';
const root = path.join(__dirname, '..');

async function source(arg) {
  if (!arg) return (await fetch(UPSTREAM)).text();
  if (/^https?:\/\//.test(arg)) return (await fetch(arg)).text();
  return fs.readFileSync(arg, 'utf8');
}

const cut = (html, name) =>
  html.split(`// ==== ${name} start ====`)[1].split(`// ==== ${name} end ====`)[0];

const raw = s => {
  if (!s.includes('\\')) {
    const escaped = s
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/\t/g, '\\t');
    return `"${escaped}"`;
  }
  let hashes = '';
  while (s.includes('"' + hashes)) hashes += '#';
  return `r${hashes}"${s}"${hashes}`;
};

const convert = (source, flags) =>
  (flags && flags.includes('i') ? '(?i)' : '') +
  source
    .replace(/\\u([0-9a-fA-F]{4})/g, (_, h) => String.fromCharCode(parseInt(h, 16)))
    .replace(/\\\//g, '/');


const describe = d => d.replace(/\s*The badge counts[^.]*\.\s*$/, '').trim();

function extractPatterns(impl) {
  const start = impl.indexOf('const patterns = [');
  const src = impl.slice(start, impl.indexOf('\n];', start) + 3);
  const scope = {
    WIKI_GROUP: 'Signs of AI writing (Wikipedia)',
    makeRegexFinder: re => ({ kind: 'regex', source: re.source, flags: re.flags }),
    makeChainFinder: head => ({ kind: 'chain', head }),
    makeEchoFinder: o => ({ kind: 'echo', ...o }),
    makeQuestionChainFinder: o => ({ kind: 'question', ...o }),
    makeAnaphoraFinder: o => ({ kind: 'anaphora', ...o }),
  };
  const build = new Function(...Object.keys(scope), `${src}; return patterns;`);
  return build(...Object.values(scope));
}

const finderExpr = find => {
  switch (find.kind) {
    case 'regex':
      return `Finder::Regex(${raw(convert(find.source, find.flags))})`;
    case 'chain':
      return `Finder::Chain(${raw(convert(find.head, ''))})`;
    case 'echo':
      return `Finder::Echo { min_gram: ${find.minGram}, min_run: ${find.minRun} }`;
    case 'question':
      return `Finder::QuestionChain { min_run: ${find.minRun} }`;
    case 'anaphora':
      return `Finder::Anaphora { min_run: ${find.minRun} }`;
    default:
      throw new Error(`unknown finder kind ${find.kind}`);
  }
};

function rulesRs(patterns) {
  const entries = patterns
    .map(
      p => `    Rule {
        id: ${raw(p.id)},
        name: ${raw(p.name)},
        description: ${raw(describe(p.description))},
        group: ${p.group === undefined ? 'None' : `Some(${raw(p.group)})`},
        finder: ${finderExpr(p.find)},
    },`
    )
    .join('\n');

  return `// @generated by tools/generate.js from Simon Willison's llm-cliche-highlighter.html
// https://github.com/simonw/tools/blob/main/llm-cliche-highlighter.html
//
// Do not edit by hand. The regex sources are the upstream JavaScript literals
// with \\uXXXX escapes resolved and an /i flag rewritten to an inline (?i).

use crate::finders::Finder;

/// A single cliché detection rule with a stable ID, a human-readable name
/// used in diagnostic output, and its corresponding pattern detector.
pub struct Rule {
    pub id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub group: Option<&'static str>,
    pub finder: Finder,
}

/// All rules in upstream declaration order. Rule order determines precedence:
/// if two rules match overlapping spans, the earlier rule takes precedence (see \`crate::lint\`).
pub static RULES: &[Rule] = &[
${entries}
];
`;
}

function casesRs(tests) {
  const start = tests.indexOf('const patternCases = [');
  const src = tests.slice(start, tests.indexOf('\n];', start) + 3);
  const cases = new Function(`${src}; return patternCases;`)();
  const rows = cases
    .map(([id, sample, expect]) => `    (${raw(id)}, ${raw(sample)}, ${expect}),`)
    .join('\n');

  return `// @generated by tools/generate.js — do not edit by hand.

/// Upstream's \`patternCases\`: (rule ID, sample text, expected match count).
///
/// Upstream also asserts item counts per chain (used for GUI badges). Because
/// the CLI does not display badge counts, only match counts are included.
pub static PATTERN_CASES: &[(&str, &str, usize)] = &[
${rows}
];
`;
}

function exampleText(impl) {
  const open = 'const EXAMPLE = `';
  const start = impl.indexOf(open) + open.length;
  return impl.slice(start, impl.indexOf('`;', start)).replace(/\\`/g, '`').replace(/\\\$/g, '$');
}

async function main() {
  const html = await source(process.argv[2]);
  const impl = cut(html, 'impl');
  const patterns = extractPatterns(impl);

  const write = (rel, body) => {
    const dest = path.join(root, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, body);
    console.log(`wrote ${rel}`);
  };

  write('src/rules.rs', rulesRs(patterns));
  write('tests/generated/cases.rs', casesRs(cut(html, 'tests')));
  write('tests/fixtures/example.txt', exampleText(impl));
  console.log(`${patterns.length} rules`);
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
