// @generated by tools/generate.js from Simon Willison's llm-cliche-highlighter.html
// https://github.com/simonw/tools/blob/main/llm-cliche-highlighter.html
//
// Do not edit by hand. The regex sources are the upstream JavaScript literals
// with \uXXXX escapes resolved and an /i flag rewritten to an inline (?i).

use crate::finders::Finder;

/// A single cliché detection rule with a stable ID, a human-readable name
/// used in diagnostic output, and its corresponding pattern detector.
pub struct Rule {
    pub id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub group: Option<&'static str>,
    pub finder: Finder,
}

/// All rules in upstream declaration order. Rule order determines precedence:
/// if two rules match overlapping spans, the earlier rule takes precedence (see `crate::lint`).
pub static RULES: &[Rule] = &[
    Rule {
        id: "no-chain",
        name: "“No X, no Y” chains",
        description: "Two or more “no …” items in a row, e.g. “No fluff, no filler, no jargon.”",
        group: None,
        finder: Finder::Chain(r"no[-\s]"),
    },
    Rule {
        id: "whole",
        name: "“That’s the whole …”",
        description: "“That / this is the whole point, game, thing …”",
        group: None,
        finder: Finder::Regex(
            r"(?i)\b(?:that|this)(?:['’]s|\s+(?:is|was))\s+the\s+whole\b(?:\s+\w+)?",
        ),
    },
    Rule {
        id: "did-not-chain",
        name: "“Did not X, did not Y” chains",
        description: "Two or more “did not …” or “didn’t …” items in a row.",
        group: None,
        finder: Finder::Chain(r"(?:did\s+not|didn['’]t)\s"),
    },
    Rule {
        id: "dont-verb-it",
        name: "“Don’t VERB it … VERB it”",
        description: "“Don’t call it X. Call it Y.” — a negated verb + “it”, then the same verb + “it” again.",
        group: None,
        finder: Finder::Regex(
            r#"(?i)\b(?:do\s+not|don['’]t)\s+(?:just\s+|simply\s+|merely\s+)?(\w+)(?:\s+(?:of|about|at|on|for|with|to))?\s+it\b[^.!?\n]*?[.!?;,:–—]['"”’]*\s*(?:just\s+|simply\s+|merely\s+)?\1(?:\s+(?:of|about|at|on|for|with|to))?\s+it\b"#,
        ),
    },
    Rule {
        id: "sit-with",
        name: "“Sit with that”",
        description: "The reflective “sit with that / this / it (for a moment)”, plus “sit with the discomfort” and friends.",
        group: None,
        finder: Finder::Regex(
            r"(?i)\bsit(?:s|ting)?\s+with\s+(?:that|this|it|(?:the|your)\s+(?:discomfort|feelings?|tension|weight|uncertainty|ambiguity|grief|silence|unease))\b(?:\s+for\s+a\s+\w+)?",
        ),
    },
    Rule {
        id: "already-know",
        name: "“You already know”",
        description: "“You already know” — the answer, what to do, or standing alone before a full stop.",
        group: None,
        finder: Finder::Regex(
            r"(?i)\byou\s+already\s+knows?\s+(?:the\s+answer|what|how|why|this|that|it|who|where)\b|\byou\s+already\s+knows?\b(?![ \t]+\w)",
        ),
    },
    Rule {
        id: "is-the-entire",
        name: "“Is the entire …”",
        description: "“X is the entire point / game / business model.”",
        group: None,
        finder: Finder::Regex(r"(?i)(?:\b(?:is|was|are|were)|['’]s)\s+the\s+entire\b(?:\s+\w+)?"),
    },
    Rule {
        id: "the-entire-is",
        name: "“The entire … is”",
        description: "“The entire point / game / business model is …” — the flipped twin of “is the entire”.",
        group: None,
        finder: Finder::Regex(
            r"(?i)\bthe\s+entire\s+[\w'’-]+(?:\s+[\w'’-]+){0,4}?\s+(?:is|was|are|were)\b",
        ),
    },
    Rule {
        id: "is-real",
        name: "“Is real … and / not”",
        description: "“The X is real, and / not …”, including “is the real … and it”. Skips “real estate”, “real time”, and similar.",
        group: None,
        finder: Finder::Regex(
            r"(?i)\bis\s+(?:(?:the|a)\s+real\b(?![\s-]+(?:estate|time|life|world|quick)\b)[^.!?\n]*?\b(?:and|not)\s+it\b|real\b(?![\s-]+(?:estate|time|life|world|quick)\b)[^.!?\n]*?\b(?:and|not)\b)",
        ),
    },
    Rule {
        id: "punchline",
        name: "“The punchline is”",
        description: "“The punchline is …”, “the punchline:”, or “the punchline?”.",
        group: None,
        finder: Finder::Regex(r"(?i)\bthe\s+punchline(?:\s+(?:is|was|being)\b|\s*[:?])"),
    },
    Rule {
        id: "worth-naming",
        name: "“Worth naming”",
        description: "The therapist-voiced “that loss is real and it’s worth naming”, “it’s worth naming that …”, or a “Worth naming:” opener. Skips “naming names”.",
        group: None,
        finder: Finder::Regex(
            r"(?i)(?:\b(?:is|are|was|were|feels?|felt|seems?|seemed)|['’]s)\s+(?:\w+\s+){0,2}?worth\s+naming\b(?!\s+names\b)|\bworth\s+naming\s*:",
        ),
    },
    Rule {
        id: "not-nothing",
        name: "“That’s not nothing”",
        description: "“That is not nothing” / “that’s not nothing”, plus the “this / it / which is not nothing” variants.",
        group: None,
        finder: Finder::Regex(
            r"(?i)\b(?:that|this|it|which)(?:['’]s|\s+(?:is|was))\s+not\s+nothing\b",
        ),
    },
    Rule {
        id: "is-the-whole",
        name: "“Is the whole …”",
        description: "Any subject + “is the whole point / trick / pitch / idea”, plus the “here is the whole …” opener. The twin of “is the entire …”, and a generalisation of “That’s the whole …” to subjects other than that/this.",
        group: None,
        finder: Finder::Regex(
            r"(?i)(?:\b(?:is|was|are|were)|['’]s)\s+the\s+whole\b(?:\s+\w+)?|\bhere(?:['’]s|\s+is)\s+the\s+whole\b(?:\s+\w+)?",
        ),
    },
    Rule {
        id: "echo-triad",
        name: "Echoing sentence runs",
        description: "Consecutive sentences built on the same repeated skeleton — “A shopping cart is an object in the system. A chat room is an object in the system.”",
        group: None,
        finder: Finder::Echo {
            min_gram: 4,
            min_run: 2,
        },
    },
    Rule {
        id: "performative-honesty",
        name: "Performative honesty",
        description: "Sincerity announced rather than demonstrated: “I won’t pretend”, “I’ll be honest”, “let’s be honest”, “to be clear”, and sentence-initial “Honestly,” or “Look,”.",
        group: None,
        finder: Finder::Regex(
            r"(?i)\bI\s+(?:will\s+not|won['’]t)\s+pretend\b|\b(?:I['’]ll|let['’]s|to)\s+be\s+(?:honest|clear|blunt|real)\b|(?:^|[.!?–—]\s+|\n)(?:Honestly|Look|Truthfully|Frankly)\s*,",
        ),
    },
    Rule {
        id: "thats-the-part",
        name: "“That’s the part …”",
        description: "Gesturing at a favoured detail instead of stating it: “that is the part a counter can’t reach”, “the part that makes me trust the rest”, “my favourite part of …”.",
        group: None,
        finder: Finder::Regex(
            r"(?i)\b(?:that|this|it)(?:['’]s|\s+(?:is|was))\s+the\s+part\b|\bthe\s+part\s+that\s+(?:makes|made|gets|got|keeps|kept)\s+(?:me|you|us|it)\b|\bmy\s+favou?rite\s+part\s+of\b",
        ),
    },
    Rule {
        id: "the-only-i-trust",
        name: "“The only X I trust”",
        description: "The narrowing superlative reveal: “the only marketing I trust”, “the only thing it needs”, “the only X that matters”.",
        group: None,
        finder: Finder::Regex(
            r"(?i)\bthe\s+only\s+[\w'’-]+(?:\s+[\w'’-]+){0,2}?\s+(?:I|you|we|it|he|she|they)\s+(?:trust|need|needs|care|want|wants|use|uses|believe)\b|\bthe\s+only\s+[\w'’-]+\s+that\s+(?:matters|counts|works|survives)\b",
        ),
    },
    Rule {
        id: "take-my-word",
        name: "“Don’t take my word for it”",
        description: "The stock invitation to verify: “you don’t have to take my word for it”, “don’t take my word for any of this”.",
        group: None,
        finder: Finder::Regex(
            r"(?i)\b(?:you\s+)?(?:do\s+not|don['’]t)\s+(?:have\s+to\s+)?take\s+my\s+word\s+for\s+(?:it|any\s+of\s+(?:it|this|that))\b",
        ),
    },
    Rule {
        id: "turns-out",
        name: "“Turns out …”",
        description: "The casual-revelation opener, almost always bolted to a tidy conclusion: “Turns out X”, “it turns out that X”.",
        group: None,
        finder: Finder::Regex(r"(?i)(?:^|[.!?–—]\s+|\n)Turns\s+out\b|\bit\s+turns\s+out\s+that\b"),
    },
    Rule {
        id: "fits-in-your-head",
        name: "“Fits in your head”",
        description: "Dev-blog boilerplate for simplicity: “small enough to hold in your head”, “batteries included”, “it just works”, “zero config”, “sane defaults”.",
        group: None,
        finder: Finder::Regex(
            r"(?i)\b(?:hold|fit|fits|holds|held)\s+(?:it\s+)?in\s+your\s+head\b|\bbatteries[-\s]included\b|\bit\s+just\s+works\b|\bzero[-\s]config(?:uration)?\b|\bsane\s+defaults\b",
        ),
    },
    Rule {
        id: "stacked-questions",
        name: "Stacked rhetorical questions",
        description: "Two or more questions fired in a row, usually fragments after the first: “Do I know how it works? Where it breaks? Which corners it cut?”",
        group: None,
        finder: Finder::QuestionChain { min_run: 2 },
    },
    Rule {
        id: "sentence-anaphora",
        name: "Repeated sentence openers",
        description: "Three or more consecutive sentences starting on the same word — “Maybe nobody needed it. Maybe it introduced … Maybe a small convenience …” Pronouns and articles are ignored.",
        group: None,
        finder: Finder::Anaphora { min_run: 3 },
    },
    Rule {
        id: "colon-triple",
        name: "Colon into a triple",
        description: "A colon opening onto three or more comma-separated items: “separate ports, processes, and local state”. The most common shape LLM prose uses to sound concrete. Noisy in technical writing — leave it off by default if your corpus is documentation.",
        group: None,
        finder: Finder::Regex(
            r":\s+[^.!?;:\n]{2,40},\s+[^.!?;:\n]{2,40},\s+(?:and\s+|or\s+)?[^.!?;:\n]{2,40}(?=[.!?\n])",
        ),
    },
    Rule {
        id: "heres-the-twist",
        name: "“Here’s the twist”",
        description: "The stage-managed reveal: “here’s the twist”, “here’s the thing”, “here’s the catch / kicker / rub”, “here’s the first example:”.",
        group: None,
        finder: Finder::Regex(
            r"(?i)\bhere(?:['’]s|\s+is)\s+(?:the|a|my|one)\s+(?:twist|thing|catch|kicker|rub|problem|first|second|third|next|recent|real|best|worst|surprising|interesting|key|important)\b[\w\s-]{0,20}[:.]",
        ),
    },
    Rule {
        id: "x-is-dead",
        name: "“X is dead”",
        description: "The obituary headline and its sequel: “peer code review is dead”, “botd is dead; long live botd”.",
        group: None,
        finder: Finder::Regex(r"(?i)\b[\w\s]{3,30}\s+(?:is|are)\s+dead\b|\blong\s+live\s+\w+"),
    },
    Rule {
        id: "thats-why-mattered",
        name: "“That’s why X mattered”",
        description: "Retroactively assigning significance: “that’s why being able to open the environment mattered”, “this is why preserving every conversation mattered”.",
        group: None,
        finder: Finder::Regex(
            r"(?i)\b(?:that|this)(?:['’]s|\s+(?:is|was))\s+why\b[^.!?\n]{0,80}?\b(?:matter(?:s|ed)?|count(?:s|ed)?)\b",
        ),
    },
    Rule {
        id: "stranded-auxiliary",
        name: "Stranded auxiliary contrast",
        description: "A clause that lands on a bare auxiliary for the reversal: “The tool died; the data didn’t.”, “Reading mostly passed … Writing didn’t”, “Maybe it wouldn’t have.”",
        group: None,
        finder: Finder::Regex(
            r"[;:,]\s+[^.;:!?\n]{2,50}\s(?:did|does|do|was|were|is|are|has|have|had|can|could|would|will)(?:n['’]t)?\s*[.;]|\b(?:Maybe|Perhaps)\s+\w+[^.!?\n]{0,40}\s(?:would|could|might|should|did|had|was|is)(?:n['’]t)?\s+(?:have\s*)?\.",
        ),
    },
    Rule {
        id: "ai-vocab",
        name: "AI vocabulary words",
        description: "Words LLMs lean on far more than people do: “delve”, “tapestry”, “meticulous”, “pivotal”, “intricate”, “interplay”, “underscore”, “garner”, “bolster”, “vibrant”, “bustling”, “multifaceted”, “seamless”, “ever-evolving”. One hit can be coincidence — several is a tell.",
        group: Some("Signs of AI writing (Wikipedia)"),
        finder: Finder::Regex(
            r"(?i)\b(?:delv(?:e|es|ed|ing)|tapestr(?:y|ies)|meticulous(?:ly)?|pivotal|intricate(?:ly)?|intricacies|interplay|underscor(?:e|es|ed|ing)|garner(?:s|ed|ing)?|bolster(?:s|ed|ing)?|vibrant|bustling|multifaceted|seamless(?:ly)?|commendable|ever-evolving)\b",
        ),
    },
    Rule {
        id: "not-just",
        name: "“Not just X, but Y”",
        description: "Negative parallelisms: “not just X, but (also) Y”, “not only … but …”, and the “it’s not X — it’s Y” contrast.",
        group: Some("Signs of AI writing (Wikipedia)"),
        finder: Finder::Regex(
            r"(?i)\bnot\s+(?:just|only|merely|simply)\s+[^.!?\n;]*?\bbut(?:\s+also)?\b|\b(?:it|this|that)(?:['’]s|\s+(?:is|was))\s+not\s+[^.!?\n,;—–]{1,60}[,;—–]\s*(?:it|this|that)(?:['’]s|\s+(?:is|was))\b",
        ),
    },
    Rule {
        id: "note-that",
        name: "“It’s important to note”",
        description: "Didactic hedging: “it is important to note that”, “it’s worth noting”, “it should be noted”, plus the “worth pausing / considering / asking” family.",
        group: Some("Signs of AI writing (Wikipedia)"),
        finder: Finder::Regex(
            r"(?i)\bit(?:['’]s|\s+(?:is|was))\s+(?:also\s+)?(?:important|worth|crucial|essential|vital)\s+(?:to\s+(?:note|remember|understand|recognize|mention|pause|consider|ask)|noting|mentioning|remembering|pausing|considering|asking)\b(?:\s+that\b)?|\bit\s+should\s+be\s+noted\b",
        ),
    },
    Rule {
        id: "testament",
        name: "“Stands as a testament”",
        description: "“Stands / serves as a testament (or reminder)”, “is a testament to” — inflating significance instead of saying what happened.",
        group: Some("Signs of AI writing (Wikipedia)"),
        finder: Finder::Regex(
            r"(?i)\b(?:stand|stands|stood|serve|serves|served|standing|serving)\s+as\s+(?:a|an)\s+(?:\w+\s+)?(?:testament|reminder)\b|\b(?:is|was|are|were|remain|remains)\s+a\s+(?:\w+\s+)?testament\s+to\b",
        ),
    },
    Rule {
        id: "crucial-role",
        name: "“Plays a crucial role”",
        description: "“Plays a crucial / pivotal / vital / key / significant role in …”.",
        group: Some("Signs of AI writing (Wikipedia)"),
        finder: Finder::Regex(
            r"(?i)\bplay(?:s|ed|ing)?\s+(?:a|an)\s+(?:\w+\s+)?(?:crucial|pivotal|vital|key|significant|central|critical|important)\s+role\b",
        ),
    },
    Rule {
        id: "landscape",
        name: "“Ever-evolving landscape”",
        description: "Scene-setting boilerplate: “the ever-evolving / changing / shifting landscape”, “in today’s fast-paced world”.",
        group: Some("Signs of AI writing (Wikipedia)"),
        finder: Finder::Regex(
            r"(?i)\b(?:ever-)?(?:evolving|changing|shifting)\s+landscape\b|\bin\s+today['’]s\s+(?:fast-paced|ever-changing|ever-evolving|digital|modern|competitive)\s+\w+",
        ),
    },
    Rule {
        id: "vague-experts",
        name: "“Experts argue”",
        description: "Vague attribution to unnamed authorities: “experts argue”, “some critics have noted”, “observers suggest”, “industry reports indicate”.",
        group: Some("Signs of AI writing (Wikipedia)"),
        finder: Finder::Regex(
            r"(?i)\b(?:many|some|several|most|numerous)?\s*(?:experts|critics|observers|scholars|analysts|commentators)\s+(?:have\s+|often\s+|widely\s+)?(?:argu(?:e|es|ed)|not(?:e|es|ed)|suggest(?:s|ed)?|believ(?:e|es|ed)|agree[ds]?|contend(?:s|ed)?|observ(?:e|es|ed)|caution(?:s|ed)?|claim(?:s|ed)?|cit(?:e|es|ed)|point(?:s|ed)?\s+out)\b|\bindustry\s+reports?\s+(?:suggest|indicate|show)\w*\b",
        ),
    },
    Rule {
        id: "despite-challenges",
        name: "“Despite these challenges”",
        description: "The boilerplate challenges-and-outlook formula: “despite these challenges”, “faces several challenges”, “challenges remain”, “remains to be seen”, “time will tell”.",
        group: Some("Signs of AI writing (Wikipedia)"),
        finder: Finder::Regex(
            r"(?i)\bdespite\s+(?:these|those|such|its|their|the|numerous|significant|ongoing)\s+(?:\w+\s+)?challenges\b|\bfac(?:e|es|ed|ing)\s+(?:several|numerous|many|significant|various|a\s+number\s+of)\s+challenges\b|\bchallenges\s+remain\b|\bremains\s+to\s+be\s+seen\b|\b(?:only\s+)?time\s+will\s+tell\b",
        ),
    },
    Rule {
        id: "participle-tail",
        name: "Participle sentence tails",
        description: "Superficial analysis bolted onto a sentence end: “…, highlighting / underscoring / showcasing / reflecting the …”.",
        group: Some("Signs of AI writing (Wikipedia)"),
        finder: Finder::Regex(
            r"(?i),\s+(?:highlighting|underscoring|emphasizing|showcasing|reflecting|demonstrating|illustrating|signaling|solidifying|cementing|reinforcing|underlining)\s+(?:its|his|her|their|our|the|a|an|how|that|what|both)\b[^.!?\n]*",
        ),
    },
    Rule {
        id: "promo",
        name: "Promotional boilerplate",
        description: "Travel-brochure tone: “nestled in”, “in the heart of”, “rich tapestry / heritage”, “hidden gem”, “boasts a”, “breathtaking”, “stunning views”.",
        group: Some("Signs of AI writing (Wikipedia)"),
        finder: Finder::Regex(
            r"(?i)\bnestled\s+(?:in|on|among|between|along|at)\b|\bin\s+the\s+heart\s+of\b|\brich\s+(?:cultural\s+|historical\s+)?(?:heritage|history|tapestry)\b|\bhidden\s+gem\b|\bmust-(?:visit|see|try)\b|\bbreathtaking\b|\bboasts?\s+(?:a|an|the)\b|\bstunning\s+(?:views?|scenery|architecture|backdrop)\b",
        ),
    },
    Rule {
        id: "ai-leftovers",
        name: "Chatbot leftovers",
        description: "Artifacts pasted straight from a chatbot: “as an AI language model”, “as of my last update”, “knowledge cutoff”, plus markup debris like “oaicite”, “contentReference”, “turn0search” and “utm_source=” tracking parameters.",
        group: Some("Signs of AI writing (Wikipedia)"),
        finder: Finder::Regex(
            r"(?i)\bas\s+an\s+ai(?:\s+language)?\s+model\b|\bas\s+of\s+my\s+last\s+(?:update|training)\b|\bknowledge\s+cutoff\b|\bI\s+(?:cannot|can['’]t|do\s+not|don['’]t)\s+(?:browse\s+the\s+internet|access\s+real-?time)\b|contentReference|oaicite|turn0(?:search|news|image)\d*|attributableIndex|utm_source=",
        ),
    },
];
